version: '3.4'

services:
  api:
    build: ./bee_build
    image: ${SERVICE_NAME}
    container_name: ${SERVICE_NAME}
    volumes:
      - gosrc:/go
      - .:/go/src/${API_BASE_DIR}/${API_NAME}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - custom.env
    environment:
      - SERVICE_TAGS=traefik.enable=true,traefik.frontend.entryPoints=http,traefik.frontend.rule=Host:${SERVICE_NAME}.localhost   
    command: sh -c 'cd ${API_BASE_DIR}/${API_NAME};go get -v ./...;  go mod init;  bee run -downdoc=true -gendoc=true'
    networks:
      - back_end
volumes:
  gosrc:
  cuentas_contables_mongo_data:
networks:
  back_end:
    external: true