version: '3.4'

services:

  api:
    build: ./bee_build
    volumes:
      - gosrc:/go
      - .:/go/src/${API_BASE_DIR}/${API_NAME}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - develop.env
    environment:
      - SERVICE_TAGS=traefik.enable=true,traefik.frontend.entryPoints=http,traefik.frontend.rule=Host:${SERVICE_NAME}.localhost
    command: sh -c 'cd ${API_BASE_DIR}/${API_NAME}; go get; bee run -downdoc=true -gendoc=true'
    # depends_on:
    #   - db
    networks:
      - back_end

  # db:
  #   image: mongo:4
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #     - MONGO_INITDB_ROOT_USERNAME=${CUENTAS_CONTABLES_CRUD_DB_USER}
  #     - MONGO_INITDB_ROOT_PASSWORD=${CUENTAS_CONTABLES_CRUD_DB_PASS}
  #   volumes:
  #     - cuentas_contables_mongo_data:/data/db
  #   ports:
  #     - ${DB_PORT}:27017
  #   networks:
  #     - back_end

volumes:
  gosrc:
  cuentas_contables_mongo_data:
networks:
  back_end:
    external: true
