swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /nodo_cuenta_contable/:
    get:
      tags:
      - nodo_cuenta_contable
      description: get all objects
      operationId: NodoCuentaContableController.GetTree
      responses:
        "200":
          description: NodoRubroApropiacion []models.NodoCuentaContable
        "403":
          description: :objectId is empty
    post:
      tags:
      - nodo_cuenta_contable
      description: Post models.NodoCuentaContable
      operationId: NodoCuentaContableController.Post models.NodoCuentaContable
      parameters:
      - in: body
        name: body
        description: Body para la creacion de models.NodoCuentaContable
        required: true
        schema:
          $ref: '#/definitions/models.NodoCuentaContable'
      responses:
        "200":
          description: '{int} models.NodoCuentaContable.Id'
        "403":
          description: body is empty
  /nodo_cuenta_contable/{UUID}:
    get:
      tags:
      - nodo_cuenta_contable
      description: get all objects
      operationId: NodoCuentaContableController.Get
      responses:
        "200":
          description: NodoRubroApropiacion models.NodoCuentaContable
        "403":
          description: :objectId is empty
definitions:
  models.NodoCuentaContable:
    title: NodoCuentaContable
    type: object
    properties:
      Codigo:
        type: string
      FechaRegistro:
        type: string
      Hijos:
        type: array
        items:
          type: string
      Padre:
        type: string
